### ISSUE TITLE
Supporting Apollo 7.0

### ISSUE THREAD

**Issue by YuqiHuai** [MingfeiCheng/AV-Fuzzer#1]
Hi @MingfeiCheng,

Thank you so much for providing this implementation! I got further in running the framework but I still could not generate any scenario.

I am running **Apollo 7.0**. I believe I did everything correctly but the Localization module won't turn on.

Do you know if there are any additional steps needed to make sure the Localization module can be turned on? Or does the overall implementation just not support the newest version of Apollo?

Thank you so much in advance.

**Comment by MingfeiCheng** [comment]
> Hi @MingfeiCheng,
> 
> Thank you so much for providing this implementation! I got further in running the framework but I still could not generate any scenario.
> 
> I am running **Apollo 7.0**. I believe I did everything correctly but the Localization module won't turn on.
> 
> Do you know if there are any additional steps needed to make sure the Localization module can be turned on? Or does the overall implementation just not support the newest version of Apollo?
> 
> Thank you so much in advance.

Hi Yuqi,
Thanks for your interest. I did not test this on Apollo 7.0. I will check and update this repo if I have time. Have you tried to open the Localization module mannually?

**Comment by YuqiHuai** [comment]
Thanks for responding!

Yes I did try to turn it on manually but couldn't do so neither.

**Comment by MingfeiCheng** [comment]
> Thanks for responding!
> 
> Yes I did try to turn it on manually but couldn't do so neither.

Ok, sorry, I m not sure the reason why the Localliazation Module can not be turned on. You can post logs if you have.. Uh... I think I will check and upload the latest version of this project after Oct. Thank you!

**Comment by YuqiHuai** [comment]
Hi sorry for the late response.

Here is the log information I got from Apollo's localization.log.INFO

```
Log file created at: 2022/09/22 10:56:26
Running on machine: in-dev-docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0922 10:56:26.219637 66362 class_loader_utility.h:79] registerclass:MSFLocalizationComponent,apollo::cyber::ComponentBase,/apollo/bazel-bin/modules/localization/msf/libmsf_localization_component.so
I0922 10:56:26.219671 66362 class_loader_utility.h:79] registerclass:MSFLocalizationComponent,apollo::cyber::ComponentBase,/apollo/bazel-bin/modules/localization/msf/libmsf_localization_component.so
I0922 10:56:26.226447 66362 msf_localization.cc:77] map: /apollo/modules/map/data/SanFrancisco/local_map
I0922 10:56:26.226455 66362 msf_localization.cc:78] lidar_extrin: /apollo/modules/localization/msf/params/velodyne_params/velodyne128_novatel_extrinsics.yaml
I0922 10:56:26.226457 66362 msf_localization.cc:79] lidar_height: /apollo/modules/localization/msf/params/velodyne_params/velodyne64_height.yaml
W0922 10:56:26.226464 66362 msf_localization.cc:87] Can't load utm zone id from map folder, use default value.
I0922 10:56:26.226464 66362 msf_localization.cc:90] utm zone id: 10
I0922 10:56:26.226471 66362 msf_localization.cc:104] Vehile imu file: /apollo/modules/localization/msf/params/vehicle_params/vehicle_imu_extrinsics.yaml
I0922 10:56:26.226816 66362 msf_localization.cc:114] imu_vehicle_quat: 0 0 0 1
I0922 10:56:26.226830 66362 msf_localization.cc:139] Ant imu lever arm file: /apollo/modules/localization/msf/params/gnss_params/ant_imu_leverarm.yaml
I0922 10:56:26.227135 66362 msf_localization.cc:152] 0 1.10866 1.14165 0.05 0.05 0.08
```

I will continue to try different configuration and see what is wrong with the localization module.

**Comment by YuqiHuai** [comment]
Hi!

I managed to get Apollo 7.0 running with your implementation.

I made a mistake myself on Dreamview. We need to select "Mkz Lgsvl" for mode.

Again thank you so much for the help!

**Comment by MingfeiCheng** [comment]
> Hi!
> 
> I managed to get Apollo 7.0 running with your implementation.
> 
> I made a mistake myself on Dreamview. We need to select "Mkz Lgsvl" for mode.
> 
> Again thank you so much for the help!

Good! 👍  Very happy to communicate with u. :)
