### ISSUE TITLE
The problem of apollo sanfrancisco map

### ISSUE THREAD

**Issue by yang-yk** [MingfeiCheng/AV-Fuzzer#2]
Hello, @MingfeiCheng,
      I am very interested in your excellent work. When I try to run the code, I found that the San Francisco map in Apollo is wrong, just like the issue described in https://github.com/ApolloAuto/apollo/issues/14341. I have tried to download the updated .bin map at https://wise.svlsimulator.com/maps/profile/12da60a7-2fc9-474d-a62a-5cc08cb97fe8. However, the problem still exists. Can you tell me how to solve the problem? Welcome to contact me via WeChat at 13146031789. Hope to Wish to hear from you soon. 

Best regards，
Yukuan Yang

**Comment by MingfeiCheng** [comment]
> Hello, @MingfeiCheng, I am very interested in your excellent work. When I try to run the code, I found that the San Francisco map in Apollo is wrong, just like the issue described in [ApolloAuto/apollo#14341](https://github.com/ApolloAuto/apollo/issues/14341). I have tried to download the updated .bin map at https://wise.svlsimulator.com/maps/profile/12da60a7-2fc9-474d-a62a-5cc08cb97fe8. However, the problem still exists. Can you tell me how to solve the problem? Welcome to contact me via WeChat at 13146031789. Hope to Wish to hear from you soon.
> 
> Best regards， Yukuan Yang

Thanks for your interest. Download the .bin file from the link your posted. And you need to convert the file into Apollo format (use this instruction https://github.com/ApolloAuto/apollo/blob/v7.0.0/modules/map/data/README.md) and put them into /apollo/modules/map/data

**Comment by yang-yk** [comment]
> > Hello, @MingfeiCheng, I am very interested in your excellent work. When I try to run the code, I found that the San Francisco map in Apollo is wrong, just like the issue described in [ApolloAuto/apollo#14341](https://github.com/ApolloAuto/apollo/issues/14341). I have tried to download the updated .bin map at https://wise.svlsimulator.com/maps/profile/12da60a7-2fc9-474d-a62a-5cc08cb97fe8. However, the problem still exists. Can you tell me how to solve the problem? Welcome to contact me via WeChat at 13146031789. Hope to Wish to hear from you soon.
> > Best regards， Yukuan Yang
> 
> Thanks for your interest. Download the .bin file from the link your posted. And you need to convert the file into Apollo format (use this instruction https://github.com/ApolloAuto/apollo/blob/v7.0.0/modules/map/data/README.md) and put them into /apollo/modules/map/data

Thanks for your kind reply. We have converted the .bin file to the Apollo format as the instruction you provide. However, the car displayed in dreamview is in the wrong position. Can you help me via WeChat(13146031789). Many thanks!

**Comment by MingfeiCheng** [comment]
> > > Hello, @MingfeiCheng, I am very interested in your excellent work. When I try to run the code, I found that the San Francisco map in Apollo is wrong, just like the issue described in [ApolloAuto/apollo#14341](https://github.com/ApolloAuto/apollo/issues/14341). I have tried to download the updated .bin map at https://wise.svlsimulator.com/maps/profile/12da60a7-2fc9-474d-a62a-5cc08cb97fe8. However, the problem still exists. Can you tell me how to solve the problem? Welcome to contact me via WeChat at 13146031789. Hope to Wish to hear from you soon.
> 
> > > Best regards， Yukuan Yang
> 
> > 
> 
> > Thanks for your interest. Download the .bin file from the link your posted. And you need to convert the file into Apollo format (use this instruction https://github.com/ApolloAuto/apollo/blob/v7.0.0/modules/map/data/README.md) and put them into /apollo/modules/map/data
> 
> 
> 
> Thanks for your kind reply. We have converted the .bin file to the Apollo format as the instruction you provide. However, the car displayed in dreamview is in the wrong position. Can you help me via WeChat(13146031789). Many thanks!

Ok. I will add ur WeChat later.

**Comment by meng2180** [comment]
Have you solved the problem? I have the same problem as you. Could you tell me how to solve the problem?

**Comment by MingfeiCheng** [comment]
> Have you solved the problem? I have the same problem as you. Could you tell me how to solve the problem?

Have you tried SanFrancisco_correct map rather than original SanFrancisco map? Could you please post more details?

**Comment by meng2180** [comment]
I&nbsp; have tested your&nbsp;SanFrancisco_correct map, but issue happened when simulate it on Windows 10 version. Particularly, from the beginning of simulation (or even after clicking Start), LGSVL on Windows only showed EV with gradient background, and without any objects such as building, road.&nbsp;









We&nbsp;are&nbsp;the&nbsp;bridge?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MingfeiCheng/AV-Fuzzer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月29日(星期三) 下午5:01
***@***.***&gt;;
抄送:&nbsp;"We are the ***@***.******@***.***&gt;;
主题:&nbsp;Re: [MingfeiCheng/AV-Fuzzer] The problem of apollo sanfrancisco map (Issue #2)





  
Have you solved the problem? I have the same problem as you. Could you tell me how to solve the problem?
  
Have you tried to use SanFrancisco_correct map rather than original SanFrancisco map? Could you please post more details?

**Comment by meng2180** [comment]
> > Have you solved the problem? I have the same problem as you. Could you tell me how to solve the problem?
> 
> Have you tried SanFrancisco_correct map rather than original SanFrancisco map? Could you please post more details?
I  have tested SanFrancisco_correct map, but issue happened when simulate it on Windows 10 version. Particularly, from the beginning of simulation (or even after clicking Start), LGSVL on Windows only showed EV with gradient background, and without any objects such as building, road.

![image](https://user-images.githubusercontent.com/39176981/228544250-4b13ef27-4bcc-4f6a-bcb6-dba00a139f04.png)

**Comment by MingfeiCheng** [comment]
> > > Have you solved the problem? I have the same problem as you. Could you tell me how to solve the problem?
> > 
> > 
> > Have you tried SanFrancisco_correct map rather than original SanFrancisco map? Could you please post more details?
> > I  have tested SanFrancisco_correct map, but issue happened when simulate it on Windows 10 version. Particularly, from the beginning of simulation (or even after clicking Start), LGSVL on Windows only showed EV with gradient background, and without any objects such as building, road.
> 
> ![image](https://user-images.githubusercontent.com/39176981/228544250-4b13ef27-4bcc-4f6a-bcb6-dba00a139f04.png)

I think you can try to modify the time in LGSVL (like set_time_of_day in python api). What is displayed in the Dreamview?

**Comment by meng2180** [comment]
> I think you can try to modify the time in LGSVL (like set_time_of_day in python api). What is displayed in the Dreamview?

DreamView seems to be normal, but there still exists a problem with LGSVL, no matter whether I modify the time in LGSVL.
![image](https://user-images.githubusercontent.com/39176981/228782921-e9cdfa14-cbf6-4fed-85b2-04a96206d5d4.png)
![image](https://user-images.githubusercontent.com/39176981/228783135-78773d89-26c2-46bc-9d32-025610899d15.png)

**Comment by MingfeiCheng** [comment]
> > I think you can try to modify the time in LGSVL (like set_time_of_day in python api). What is displayed in the Dreamview?
> 
> DreamView seems to be normal, but there still exists a problem with LGSVL, no matter whether I modify the time in LGSVL. ![image](https://user-images.githubusercontent.com/39176981/228782921-e9cdfa14-cbf6-4fed-85b2-04a96206d5d4.png) ![image](https://user-images.githubusercontent.com/39176981/228783135-78773d89-26c2-46bc-9d32-025610899d15.png)

Uh... Because the online LGSVL was crashed, I am not sure why... It seems the Map was not loaded well in the LGSVL..

**Comment by cfs4819** [comment]
Sorry for making this issue active again. But since `wise` has stopped maintenance, where can I download the available SanFrancisco_correct map so that I can put them in `apollo/modules/maps/data`?
Maybe another Google Drive is OK for me.
Thanks Sincerely！
