### ISSUE TITLE
.obj文件如何打开

### ISSUE THREAD

**Issue by looles** [MingfeiCheng/AV-Fuzzer#3]
您好，
![图片](https://github.com/MingfeiCheng/AV-Fuzzer-Reimplement/assets/44311409/48365eb6-9ff1-4e6b-b9a8-fe85047f8492)
请问生成的.obj文件如何打开查看？

**Comment by MingfeiCheng** [comment]
You can load this data by 
```
with open(file, 'rb') as f:
    data = pickle.load(f)
```

The data format of these scenario obj files can be found at `line 218` in [genetic_algorithm.py](https://github.com/MingfeiCheng/AV-Fuzzer-Reimplement/blob/main/mutation/genetic_algorithm.py).

**Comment by looles** [comment]
您好，我使用meshlab软件为什么打不开.obj文件？

**Comment by looles** [comment]
有推荐可以可视化.obj文件的软件吗？

**Comment by MingfeiCheng** [comment]
.obj文件是自定义的，用于保存scenario参数。这个可能需要自己写脚本来可视化。

**Comment by looles** [comment]
好的，十分感谢。
