### ISSUE TITLE
地图坐标

### ISSUE THREAD

**Issue by looles** [MingfeiCheng/AV-Fuzzer#4]
冒昧又来叨扰了，大神，我想更改一下npc的位置还有数量，请问如何知道地图上的点代表的坐标呢？（您当时定坐标的时候是如何定义的？）
![image](https://github.com/MingfeiCheng/AV-Fuzzer-Reimplement/assets/44311409/9c9471a1-88eb-4995-86f2-5f4b000226a1)

**Comment by MingfeiCheng** [comment]
参数和场景是手动定义的，地图信息可以通过LGSVL查看 （如果还可用的话）

**Comment by looles** [comment]
LGSVL不能用了，请问还有别的工具可以查看.bin地图文件的坐标吗？

**Comment by MingfeiCheng** [comment]
OpenDRIVE格式地图的话可以用 https://odrviewer.io/
Apollo格式的话可以用 https://ntutangyun.github.io/apollo-hd-map-viewer/

**Comment by looles** [comment]
地图文件格式是apollo的.bin文件，但是获取的坐标格式好像和您定义的坐标格式不是同一种，请问如何转换坐标？或者您那边有sanfrasnscisco_correct.xodr地图文件吗？有的话，可以发我一份吗？十分感谢
![image](https://github.com/MingfeiCheng/AV-Fuzzer-Reimplement/assets/44311409/3c0e9055-79f0-4a36-a3fd-2b3d24ce1ae7)
![image](https://github.com/MingfeiCheng/AV-Fuzzer-Reimplement/assets/44311409/e6346ad6-d431-4f79-a60a-380f450ab820)

**Comment by MingfeiCheng** [comment]
不好意思，LGSVL的原始地图文件我这里也没有了

**Comment by looles** [comment]
谢谢您的帮助！！！
